[{
		"red":"fa-facebook",
		"estilo":"facebookBlanco",
		"url":"https://facebook.com/"
	},{
		"red":"fa-youtube",
		"estilo":"youtubeBlanco",
		"url":"https://youtube.com/"
	},{
		"red":"fa-twitter",
		"estilo":"twitterBlanco",
		"url":"https://twitter.com/"
	},{
		"red":"fa-google-plus",
		"estilo":"googleBlanco",
		"url":"https://google.com/"
	},{
		"red":"fa-instagram",
		"estilo":"instagramBlanco",
		"url":"https://instagram.com/"
	}
]
